name: Build Tiny_Swizzles


on:

  push:
    branches: [ master, add_github_action ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: [macos-latest]
    env:
      XC_VERSION: ${{ '12.4' }}
      XC_PROJECT: ${{ 'tinyDormant.xcodeproj' }}
      XC_SCHEME: ${{ 'tinyDormant' }}

    steps:
    - name: Select latest Xcode
      run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
    - uses: actions/checkout@v2
    - name: Simulator app builds
      run: /usr/bin/xcodebuild -project "$XC_PROJECT" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 11'


